version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - pip install --upgrade requests -t .
      - >-
        aws cloudformation package --template template.yaml --s3-bucket
        hrmd-lambda-image-test --output-template template-export.yaml
  post_build:
    commands:
      - echo Build completed on `date`
      - pwd
      - ls -al
artifacts:
  files:
    - '**/*'
